name: Publish to npm

env:
  PROTO_TELEMETRY: false

on:
  # Only ran after a new GitHub release is published
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      # Required for OIDC to let npm registry know
      # that this workflow is trusted
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Proto
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: Node Version
        run: node -v
      - name: npm Version
        # OIDC requires npm 11.5.1 or above
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
